[package]
name = "verilogls"
version = "0.1.0"
authors = ["Vivek Malneedi <vivekmalneedi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sv-parser = "0.7.0"
log = "0.4.11"
tower-lsp = "0.11.0"
flexi_logger = "0.15.10"
ropey = "1.2.0"
tokio = { version = "0.2.22", features = ["full"] }
path-clean = "0.1.0"

verilogls_slang_wrapper = { path = "verilogls_slang_wrapper" }
