[package]
name = "veridian"
version = "0.1.0"
authors = ["Vivek Malneedi <vivekmalneedi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sv-parser = "0.8.2"
log = "0.4.11"
tower-lsp = "0.13.3"
flexi_logger = "0.16.1"
ropey = "1.2.0"
tokio = { version = "0.2.22", features = ["macros", "io-std", "rt-threaded"] }
path-clean = "0.1.0"
pathdiff = "0.2.0"
walkdir = "2.3.1"
serde_yaml = "0.8.13"
anyhow = "1.0.33"
serde = "1.0.117"
which = "4.0.2"

veridian_slang = { path = "veridian-slang" }
structopt = "0.3.20"
