on: [push, pull_request]

name: CI

jobs:
  build_vscode:
    name: Build vscode extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
          check-latest: true
      - name: build extension
        working-directory: extensions/vscode
        run: |
          npm install
          npm install vsce
          vsce package -o veridian.vsix

      - uses: actions/upload-artifact@v2
        with:
          name: veridian.vsix
          path: extensions/vscode/veridian.vsix
          if-no-files-found: error

  publish:
    name: Create Release
    needs: build_vscode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: veridian.vsix
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "nightly"
          files: |
            veridian.vsix
